# http://lint.travis-ci.org/
# http://docs.travis-ci.com/user/build-configuration/
language: ruby

matrix:
  include:
    # latest Rails; Old Rubies: 1.9.3   2.0.0   2.1.5
    - rvm: 1.9.3
      gemfile: gemfiles/rails-4-2-stable.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails-4-2-stable.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/rails-4-2-stable.gemfile

    # latest Ruby, old Rails: 4-0-stable   4-1-stable
    - rvm: 2.2.1
      gemfile: gemfiles/rails-4-0-stable.gemfile
    - rvm: 2.2.1
      gemfile: gemfiles/rails-4-1-stable.gemfile

    # both latest
    - rvm: 2.2.1
      gemfile: gemfiles/rails-4-2-stable.gemfile

    # latest Ruby, next Rails
    # - rvm: 2.2.1
    #   gemfile: gemfiles/rails-master.gemfile
cache:
  - bundler
  - apt
addons:
  code_climate:
    repo_token: 6aaf7f088c020571433a2ddd872072efcbe05aba1b68d66ed96593e8d101a74d