# http://lint.travis-ci.org/
# http://docs.travis-ci.com/user/build-configuration/
language: ruby
sudo: false
rvm: 2.3.0

matrix:
  include:
    - gemfile: gemfiles/rails-4-2-stable.gemfile
    - gemfile: gemfiles/rails-master.gemfile
  allow_failures:
    # allowed to fail because of a temporary change
    - gemfile: gemfiles/rails-master.gemfile
cache:
  - bundler
  - apt
addons:
  code_climate:
    repo_token: 6aaf7f088c020571433a2ddd872072efcbe05aba1b68d66ed96593e8d101a74d
